### ISSUE TITLE
Bowdoin Glacier

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/greenland_ice_borehole_temperature_profiles#46]
Paper: http://doi.org/10.3389/feart.2020.00065

Data:  http://doi.org/10.5281/zenodo.3695961

**Comment by juseg** [comment]
Thank you for your compilation effort! The Bowdoin Glacier data are not trivial indeed. I found my way to this issue and answer your email points below.

> If you have temperature at multiple times, just use the last, presumably when the system is in post-drilling equilibrium.

The story seems to be a bit more complicated at Bowdoin Glacier, so I want to ask for your opinion. We have three-year timeseries. For three-six months the boreholes cool down from drilling, then they warm up due to (we think) latent heat from crevasses. Everyone was surprised how deep and strong the warming is. From three months onward we progressively loose sensors to creep.

It is difficult to pick an optimal date, but I suggest those corresponding to solid lines in our 2020 paper [Fig. 4](https://www.frontiersin.org/articles/10.3389/feart.2020.00065/full#F4) (2014-10-01 and 2015-01-01, see below). These are towards the early part when we have more sensors, but the drilling perturbation is (mostly) over.

> I'm still not totally familiar with your data, but we could add 6 profiles:
> 
> - bowdoin.bh1.inc.temp.csv
> - bowdoin.bh2.pzm.temp.csv
> - bowdoin.bh2.thr.temp.csv
> - bowdoin.bh3.inc.temp.csv
> - bowdoin.bh3.pzm.temp.csv
> - bowdoin.bh3.thr.temp.csv
> 
> Or 3: bh1, bh2, and bh3 where each is a hybrid/virtual profile made from multiple sensors, either interleaved by depth, or averaged if multiple sensors at the same depth on different strings, etc. I leave the implementation details to you.

I suggest three profiles. Measurements are consistent across sensor types, except for some thermistors that seem to have been misplaced (gray lines in the figure), and which I would exclude. BH1 and BH2 are only 10m apart but show some differences. BH3 is 1km away and much warmer. 

I link the figure below. Profiles on the left, theoretical diffusive and observed change in temperature on the right. Only the green profile combines different sensor types (markers).

![Bowdoin profiles](https://www.frontiersin.org/files/Articles/510434/feart-08-00065-HTML/image_m/feart-08-00065-g004.jpg)

I can contribute by pull request by Jan 1st.

**Comment by mankoff** [comment]
I agree that the profiles in the paper would be the best to contribute to this dataset.
